/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserMeasurementsService } from "../userMeasurements.service";
import { UserMeasurementsCreateInput } from "./UserMeasurementsCreateInput";
import { UserMeasurements } from "./UserMeasurements";
import { UserMeasurementsFindManyArgs } from "./UserMeasurementsFindManyArgs";
import { UserMeasurementsWhereUniqueInput } from "./UserMeasurementsWhereUniqueInput";
import { UserMeasurementsUpdateInput } from "./UserMeasurementsUpdateInput";
import { FitPredictionFindManyArgs } from "../../fitPrediction/base/FitPredictionFindManyArgs";
import { FitPrediction } from "../../fitPrediction/base/FitPrediction";
import { FitPredictionWhereUniqueInput } from "../../fitPrediction/base/FitPredictionWhereUniqueInput";

export class UserMeasurementsControllerBase {
  constructor(protected readonly service: UserMeasurementsService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserMeasurements })
  async createUserMeasurements(
    @common.Body() data: UserMeasurementsCreateInput
  ): Promise<UserMeasurements> {
    return await this.service.createUserMeasurements({
      data: data,
      select: {
        armLength: true,
        bust: true,
        createdAt: true,
        gender: true,
        height: true,
        hips: true,
        id: true,
        inseam: true,
        shoulderWidth: true,
        updatedAt: true,
        waist: true,
        weight: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [UserMeasurements] })
  @ApiNestedQuery(UserMeasurementsFindManyArgs)
  async userMeasurementsItems(
    @common.Req() request: Request
  ): Promise<UserMeasurements[]> {
    const args = plainToClass(UserMeasurementsFindManyArgs, request.query);
    return this.service.userMeasurementsItems({
      ...args,
      select: {
        armLength: true,
        bust: true,
        createdAt: true,
        gender: true,
        height: true,
        hips: true,
        id: true,
        inseam: true,
        shoulderWidth: true,
        updatedAt: true,
        waist: true,
        weight: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserMeasurements })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async userMeasurements(
    @common.Param() params: UserMeasurementsWhereUniqueInput
  ): Promise<UserMeasurements | null> {
    const result = await this.service.userMeasurements({
      where: params,
      select: {
        armLength: true,
        bust: true,
        createdAt: true,
        gender: true,
        height: true,
        hips: true,
        id: true,
        inseam: true,
        shoulderWidth: true,
        updatedAt: true,
        waist: true,
        weight: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserMeasurements })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUserMeasurements(
    @common.Param() params: UserMeasurementsWhereUniqueInput,
    @common.Body() data: UserMeasurementsUpdateInput
  ): Promise<UserMeasurements | null> {
    try {
      return await this.service.updateUserMeasurements({
        where: params,
        data: data,
        select: {
          armLength: true,
          bust: true,
          createdAt: true,
          gender: true,
          height: true,
          hips: true,
          id: true,
          inseam: true,
          shoulderWidth: true,
          updatedAt: true,
          waist: true,
          weight: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserMeasurements })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUserMeasurements(
    @common.Param() params: UserMeasurementsWhereUniqueInput
  ): Promise<UserMeasurements | null> {
    try {
      return await this.service.deleteUserMeasurements({
        where: params,
        select: {
          armLength: true,
          bust: true,
          createdAt: true,
          gender: true,
          height: true,
          hips: true,
          id: true,
          inseam: true,
          shoulderWidth: true,
          updatedAt: true,
          waist: true,
          weight: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/fitPredictions")
  @ApiNestedQuery(FitPredictionFindManyArgs)
  async findFitPredictions(
    @common.Req() request: Request,
    @common.Param() params: UserMeasurementsWhereUniqueInput
  ): Promise<FitPrediction[]> {
    const query = plainToClass(FitPredictionFindManyArgs, request.query);
    const results = await this.service.findFitPredictions(params.id, {
      ...query,
      select: {
        createdAt: true,
        fitRating: true,
        fitScore: true,

        garment: {
          select: {
            id: true,
          },
        },

        id: true,
        recommendation: true,
        updatedAt: true,

        userMeasurement: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/fitPredictions")
  async connectFitPredictions(
    @common.Param() params: UserMeasurementsWhereUniqueInput,
    @common.Body() body: FitPredictionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fitPredictions: {
        connect: body,
      },
    };
    await this.service.updateUserMeasurements({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/fitPredictions")
  async updateFitPredictions(
    @common.Param() params: UserMeasurementsWhereUniqueInput,
    @common.Body() body: FitPredictionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fitPredictions: {
        set: body,
      },
    };
    await this.service.updateUserMeasurements({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/fitPredictions")
  async disconnectFitPredictions(
    @common.Param() params: UserMeasurementsWhereUniqueInput,
    @common.Body() body: FitPredictionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fitPredictions: {
        disconnect: body,
      },
    };
    await this.service.updateUserMeasurements({
      where: params,
      data,
      select: { id: true },
    });
  }
}
