/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsString,
  MaxLength,
  IsOptional,
  IsEnum,
  IsBoolean,
  ValidateNested,
  IsNumber,
  Min,
  Max,
} from "class-validator";

import { EnumGarmentCategory } from "./EnumGarmentCategory";
import { FitPredictionUpdateManyWithoutGarmentsInput } from "./FitPredictionUpdateManyWithoutGarmentsInput";
import { Type } from "class-transformer";

@InputType()
class GarmentUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  brand?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumGarmentCategory,
  })
  @IsEnum(EnumGarmentCategory)
  @IsOptional()
  @Field(() => EnumGarmentCategory, {
    nullable: true,
  })
  category?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  elasticity?: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fabricType?: string | null;

  @ApiProperty({
    required: false,
    type: () => FitPredictionUpdateManyWithoutGarmentsInput,
  })
  @ValidateNested()
  @Type(() => FitPredictionUpdateManyWithoutGarmentsInput)
  @IsOptional()
  @Field(() => FitPredictionUpdateManyWithoutGarmentsInput, {
    nullable: true,
  })
  fitPredictions?: FitPredictionUpdateManyWithoutGarmentsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fitType?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  length?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  productId?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  shoulder?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  size?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  width?: number | null;
}

export { GarmentUpdateInput as GarmentUpdateInput };
